# Generated by Django 4.2.7 on 2023-11-06 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_myuser_first_name_alter_myuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
